name: Laravel CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: test_user
                    MYSQL_PASSWORD: test_pass
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: リポジトリをチェックアウト
              uses: actions/checkout@v4

            - name: PHP のセットアップ
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, bcmath, pdo_mysql, xdebug
                  coverage: none

            - name: Composer のキャッシュ
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: composer-

            - name: 依存関係のインストール
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Node.js のセットアップ
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: 依存関係のインストール(Node.js)
              run: npm ci

            - name: Vite ビルド
              run: npm run build

            - name: .env.testing のセットアップ
              run: cp .env.testing .env

            - name: アプリキーの生成
              run: php artisan key:generate

            - name: データベースのマイグレーション
              run: php artisan migrate --env=testing

            - name: テストの実行
              run: php artisan test
